<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_pagination</name>
   <tag></tag>
   <elementGuidId>98971763-cf84-48b5-9602-93f37fb8dbf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/main/div/div/div[3]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.items-center.justify-between.px-6.py-4.border-t.border-gray-200.bg-white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Trang 1 / 1 Trước 1 Sau&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2d6074ef-3825-461a-90b3-a5b587f7b235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-between px-6 py-4 border-t border-gray-200 bg-white</value>
      <webElementGuid>5a3e4c76-7f5a-4f81-9600-566ec9fba5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Trang 1 / 1 Trước 1 Sau </value>
      <webElementGuid>e478cb33-f891-404d-b0a2-c6475fecf2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;flex h-screen bg-gray-100&quot;]/div[@class=&quot;flex-1 flex flex-col overflow-hidden transition-all duration-300 ease-in-out ml-0&quot;]/main[@class=&quot;flex-1 overflow-y-auto&quot;]/div[@class=&quot;p-6&quot;]/div[@class=&quot;space-y-6&quot;]/div[@class=&quot;card relative&quot;]/div[@class=&quot;flex items-center justify-between px-6 py-4 border-t border-gray-200 bg-white&quot;]</value>
      <webElementGuid>dd50df7f-ffe3-4966-a04a-0dc2bee35254</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/main/div/div/div[3]/div[2]</value>
      <webElementGuid>f88e4765-930d-4248-9184-76fd2c0715df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xóa'])[1]/following::div[1]</value>
      <webElementGuid>37e96686-0d53-428d-a4df-44e000dbc65b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sửa'])[1]/following::div[1]</value>
      <webElementGuid>00d848e9-3b72-472a-a870-6ec6fe8b6cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]</value>
      <webElementGuid>fdd4a691-cd05-4c4a-82bc-d02364dab5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Trang 1 / 1 Trước 1 Sau ' or . = 'Trang 1 / 1 Trước 1 Sau ')]</value>
      <webElementGuid>dd8b322d-bd71-4e7a-96dc-ccd70bf8a320</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
