<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_check_isCore</name>
   <tag></tag>
   <elementGuidId>178fa2fd-fd82-4d39-b5aa-3afe8543f80a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(2) > label.flex.items-center.gap-2 > input.rounded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Năng lực lõi (Core)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3b89b47-80ce-4ff0-8346-5150178936f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5e852dc0-2ce4-4aff-bea4-ea0e1108ce75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded</value>
      <webElementGuid>a279c382-166a-48e9-a50d-5e9e7cd8a297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;competency-form&quot;)/div[2]/label[@class=&quot;flex items-center gap-2&quot;]/input[@class=&quot;rounded&quot;]</value>
      <webElementGuid>bd3ad544-1775-4948-a893-c5d90ff372da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[5]</value>
      <webElementGuid>6284d906-c529-4726-8bae-4b1b595883eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='competency-form']/div[2]/label/input</value>
      <webElementGuid>9cc44706-a481-46ac-94ee-aed0d060793b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>acbca816-997d-45db-957e-ddb08268eb0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>d63e254f-8f64-4e20-b0d4-ac5873bf80fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
